[package]
name = "smtp-server"
version = "0.1.0"
authors = ["Léo Gaspard <leo@gaspard.io>"]
license = "MIT"
categories = ["email", "network-programming"]
keywords = ["smtp", "server", "asynchronous", "email"]
description = "SMTP server library using tokio"
edition = "2018"

[dependencies]
bytes = "0.4.6"
futures = "0.3.4"
itertools = "0.9.0"

smtp-message = { path = "../smtp-message" }
